### ISSUE TITLE
Getting an error when using predict: x has to be a numeric matrix.

### ISSUE THREAD

**Issue by nadavPyAn** [mhahsler/dbscan#52]
originally i was using the following code to create a model and make prediction (for simplicity i'm making predictions on the learning data itself):

model=dbscan(learnData,0.5,minPts =7);
predict(model,testData,learnData)

in R 3.6.0 the code used to work fine. we upgraded to R 4.0.2 (and therefore newer dbscan) and it stopped working with the following error:

**Error in frNN(data, query = newdata, eps = eps, sort = TRUE, ...) : 
  x has to be a numeric matrix.**

I found this issue that looks the same, but was closed:
https://github.com/mhahsler/dbscan/issues/14

I even tried the code that was given in the closed issue as an example but it also fails with the same error:

**library('dbscan')
data(iris)
d <- cluster::daisy(iris, metric = "gower", stand = TRUE)
model <- dbscan(d, eps = .23, minPts = 50)
predict(model, newdata = iris[1:5,], data = iris)**

I also tried upgrading to R 4.2.1, and made sure i'm with dbscan_1.1-10. but still i'm getting the same error.

**Comment by mhahsler** [comment]
The issue is that the species for iris is not a numeric matrix so Euclidean distance cannot be calculated. In older versions, it might have worked because it quietly converted the factor to integers and used Euclidean distances.

You can replicate that behavior using:

library('dbscan')
data(iris)
d <- cluster::daisy(iris, metric = "gower", stand = TRUE)
model <- dbscan(d, eps = .23, minPts = 50)

iris[,5] <- as.numeric(iris[,5])
predict(model, newdata = iris[1:5,], data = iris)

However, this is not ideal.

**Comment by mhahsler** [comment]
I have pushed changes to GitHub. The following code should now run with several warnings:

```
library('dbscan')
data(iris)
d <- as.dist(cluster::daisy(iris, metric = "gower", stand = TRUE))
model <- dbscan(d, eps = .23, minPts = 50)
predict(model, newdata = iris[1:5,], data = iris)
```
